language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test-requirements.txt --use-mirrors
script:
  # python openstack_auth/tests/run_tests.py
  - python setup.py test
matrix:
  allow_failures:
    - python: "3.3"
